### ISSUE TITLE
Can LFM handle explicit inputs (CV, gate) from other modules?

### ISSUE THREAD

**Issue by jimallman** [kockie69/Visualizer#17]
From what I'm reading, projectM and Milkdrop tease just a few inputs from the audio stream:
- amplitude of bass/mid/high frequencies
- beat detection
- anything else?

It would be a huge improvement if we could add several inputs that receive CV/gates/triggers as well. I don't know how hard it would be to make shaders that respond to these values. If that's not feasible, perhaps they could be used to override the values above?

This would give some of the richness of TouchDesigner and the like, which can be explicitly influenced via MID or OSC.

**Comment by jimallman** [comment]
Looking at an old MilkDrop docs, there are two promising mechanisms we might take advantage of here: [author-declared variables](http://wiki.winamp.com/wiki/MilkDrop_Preset_Authoring#VARIABLE_POOLS.3B_DECLARING_YOUR_OWN_VARIABLES.3B_PERSISTENCE_OF_VALUES) and ['Q' variables](http://wiki.winamp.com/wiki/MilkDrop_Preset_Authoring#PRESET_INIT_CODE.3B_CARRYING_VALUES_BETWEEN_VARIABLE_POOLS.2C_USING_q1-q32). I gather these are variables that can be used within per-frame and per-pixel equations. In the first case, we could let the Rack user map each input to a variable name (editable text); in the latter, we could simply offer up to 32 inputs (maybe via an expander?) and pass these into any running preset.

I gather these might only be useful in presets that anticipate them, so this might make more sense if there's a way to add custom presets to LFM.

**Comment by kockie69** [comment]
Adding custom presets is no problem, they can be copied in the presets
folder of the plugin. At the moment projectm is changing their api and
removing a lot I.e. the toast messages. So at the moment I am actually
waiting to see what their final offering will look like.

**Comment by kockie69** [comment]
What is touchdesigner? I googled it but what does it do that makes it cool?

**Comment by jimallman** [comment]
TouchDesigner is sort of a modular video synth, comparable to VCV Rack but for visualization. It's widely used in live performance, with projection mapping, etc. Some examples:
https://derivative.ca/showcase

Here are some demos using OSC to pair TD with VCV Rack:
https://www.youtube.com/watch?v=56QdSo4TFqo
https://derivative.ca/community-post/tutorial/setting-audiovisual-performance-vcv-rack-and-touchdesigner/62724

**Comment by kockie69** [comment]
On your original question, the parameters we can control in theory are in projectM.h. So a couple I have implemented, we can do a bit more.

**Comment by kockie69** [comment]
I have now added CV's for:
Next preset
Previous presets
Beat sensitivity
Hardcut sensitivity

This can all be tested from the development branch.

**Comment by jimallman** [comment]
> Looking at an old MilkDrop docs, there are two promising mechanisms we might take advantage of here: [author-declared variables](http://wiki.winamp.com/wiki/MilkDrop_Preset_Authoring#VARIABLE_POOLS.3B_DECLARING_YOUR_OWN_VARIABLES.3B_PERSISTENCE_OF_VALUES) and ['Q' variables](http://wiki.winamp.com/wiki/MilkDrop_Preset_Authoring#PRESET_INIT_CODE.3B_CARRYING_VALUES_BETWEEN_VARIABLE_POOLS.2C_USING_q1-q32). I gather these are variables that can be used within per-frame and per-pixel equations.


Just to follow up on this issue, I [asked in the projectM #development channel](https://discord.com/channels/737206408482914387/737600388944887819/1043905781826859018) about an API call to set Q (or T) variables that would update in each frame, and got a pretty firm no:

> _jima23 — Today at 10:08 AM_
> Speaking of setters and getters, is there an API call to set Q variables on-the-fly, to modify the current preset as it plays? This would be fantastic for host apps like VCV Rack that could modulate these variables to drive the viz in interesting ways.
>
> _jima23 — Today at 10:51 AM_
> I gather these values are "reset" within  the preset on every frame, so I'm hoping an incoming value could just update for the next frame.
>
> _CodAv — Today at 10:59 AM_
> Since each preset uses the q/t variables for completely arbitrary purposes, there's not really any point in changing the values. Especially given the fact that they are initialized once per frame, then changed and passed on from expression to expression. Making it possible to manipulate this from the outside would mean you need to hook into the actual expression evaluation parser, waiting for the "right moment" to change the value, then continue execution.
> 
> So at least from my point of view, **that's something projectM will never provide via the official sources or API** as it's highly specialized and will only work with well-know presets for a select number of use cases. 
>
> jima23 — Today at 2:53 PM
> Understood. I had assumed people could write shaders that could respond to a changing q/t variable; I was certainly interested in doing so.

Without this feature, I'll probably turn my attention to TouchDesigner which accepts OSC messages. Unless we want to try mutating a fork of projectM? Maybe it's not that hard a change to make. 

All that said, I realize the audience for this set of features might be **just me** at this point, so I'll let it drop unless you're interested.
