### ISSUE TITLE
Can we show beat detection and low/mid/high amplitude?

### ISSUE THREAD

**Issue by jimallman** [kockie69/Visualizer#19]
I'm wondering if we could see some explicit feedback (presumably via right-click menu option) on how projectM is interpreting the input audio in terms of beats and low/mid/high amplitude. 

I keep trying different beat-sensitivity levels and passing in simple, thumping drum sounds, and I can't see any matching movement in the presets I've tried. Are there presets that are particularly sensitive to beat detection? to amplitude changes?

ETA I'm testing on an M1 Mac, with both the embedded and full LFM visualizers.

**Comment by kockie69** [comment]
Well the sensitivity should work for most presets. And when I increase it I
can definitely notice. At the moment hard and soft beat sense need
implementation. We should add knobs for them. Feedback from projectm isn't
available as far as I know but of course you will see the setting from the
knob. But I am not an expert on projectm, so any knowledge sharing is
helpful.

**Comment by jimallman** [comment]
I've been looking for API docs (even a draft) and not finding them; apparently, they're trying to finalize the API before adding docs. Meanwhile, the beat detection on Mac seems broken to me. Every time I _think_ it's working, I've tried changing the tempo of the incoming drumbeat, and the viz does not change.

**Comment by kockie69** [comment]
I am travelling back from the Netherlands to the UK at the moment. I will
have a look tomorrow.  Maybe we should add some extra debug for Mac to see
what is happening.

**Comment by jimallman** [comment]
I'm bouncing a test patch back and forth between Mac and Windows, and that has helped me to better understand the beat detection.

I can now see beat detection on Mac _if_ the input audio is high enough amplitude (> 2V), esp when using the `Geiss - Dynamic Swirls` (all) and `Aderrasi - Antique Abyss` presets. So maybe all is fine on Mac? But yeah, some diagnostic feedback would be helpful here.

**Comment by kockie69** [comment]
I have created a new branch called development. I have added a knob to control the sensitivity (I removed the 2 buttons). We can add and input CV now too to control the sensitivity. Please make changes to this development branch please. If stable we can push to main for release.

**Comment by jimallman** [comment]
Cool, will do.

**Comment by kockie69** [comment]
Oh by the way, I have sent new version to VCV yesterday. So hopefully it will be released soon

**Comment by kockie69** [comment]
I have fixed an issue today. Now the module is responding perfectly. I also send you a pm in vcv. I am closing this one now.
