### ISSUE TITLE
Spewing lots of stuff to stdout

### ISSUE THREAD

**Issue by ContemporaryInsanity** [kockie69/Visualizer#20]
At a brief glance I assume your module is responsible, you might want to fix it?  Different debug & release builds maybe.

Failed to parse HLSL(step2) Comp shader
Source: 
uniform float4 texsize_pw_main;
uniform float4 texsize_pc_main;
uniform float4 texsize_noisevol_lq;
uniform float4 texsize_noisevol_hq;
uniform float4 texsize_noise_mq;
uniform float4 texsize_noise_lq_lite;
uniform float4 texsize_noise_lq;
uniform float4 texsize_noise_hq;
uniform float4 texsize_main;
uniform float4 texsize_fw_main;
uniform float4 texsize_fc_main;
uniform sampler2D sampler_pw_main;
uniform sampler2D sampler_pc_main;
uniform sampler3D sampler_noisevol_lq;
uniform sampler3D sampler_noisevol_hq;
uniform sampler2D sampler_noise_mq;
uniform sampler2D sampler_noise_lq_lite;
uniform sampler2D sampler_noise_lq;
uniform sampler2D sampler_noise_hq;
uniform sampler2D sampler_main;
uniform sampler2D sampler_fw_main;
uniform sampler2D sampler_fc_main;

uniform float4   rand_frame;    // random float4, updated each frame
uniform float4   rand_preset;   // random float4, updated once per *preset*
uniform float4   _c0;           // .xy: multiplier to use on UV's to paste
                                // an image fullscreen, *aspect-aware*
                                // .zw = inverse.
uniform float4   _c1, _c2, _c3, _c4;
uniform float4   _c5;           // .xy = scale, bias for reading blur1
                                // .zw = scale, bias for reading blur2
uniform float4   _c6;           // .xy = scale, bias for reading blur3
                                // .zw = blur1_min, blur1_max
uniform float4   _c7;           // .xy ~= float2(1024,768)
                                // .zw ~= float2(1/1024.0, 1/768.0)
uniform float4   _c8;           // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.3, ~1.3, ~5, ~20))
uniform float4   _c9;           // .xyzw ~= same, but using sin()
uniform float4   _c10;          // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.005, ~0.008, ~0.013,
                                //                 ~0.022))
uniform float4   _c11;          // .xyzw ~= same, but using sin()
uniform float4   _c12;          // .xyz = mip info for main image
                                // (.x=#across, .y=#down, .z=avg)
                                // .w = unused
uniform float4   _c13;          // .xy = blur2_min, blur2_max
                                // .zw = blur3_min, blur3_max
uniform float4   _qa;           // q vars bank 1 [q1-q4]
uniform float4   _qb;           // q vars bank 2 [q5-q8]
uniform float4   _qc;           // q vars ...
uniform float4   _qd;           // q vars
uniform float4   _qe;           // q vars
uniform float4   _qf;           // q vars
uniform float4   _qg;           // q vars
uniform float4   _qh;           // q vars bank 8 [q29-q32]

// note: in general, don't use the current time w/the *dynamic* rotations!

// four random, static rotations, randomized at preset load time.
// minor translation component (<1).
uniform float4x3 rot_s1;
uniform float4x3 rot_s2;
uniform float4x3 rot_s3;
uniform float4x3 rot_s4;

// four random, slowly changing rotations.
uniform float4x3 rot_d1;
uniform float4x3 rot_d2;
uniform float4x3 rot_d3;
uniform float4x3 rot_d4;

// faster-changing.
uniform float4x3 rot_f1;
uniform float4x3 rot_f2;
uniform float4x3 rot_f3;
uniform float4x3 rot_f4;

// very-fast-changing.
uniform float4x3 rot_vf1;
uniform float4x3 rot_vf2;
uniform float4x3 rot_vf3;
uniform float4x3 rot_vf4;

// ultra-fast-changing.
uniform float4x3 rot_uf1;
uniform float4x3 rot_uf2;
uniform float4x3 rot_uf3;
uniform float4x3 rot_uf4;

// Random every frame.
uniform float4x3 rot_rand1;
uniform float4x3 rot_rand2;
uniform float4x3 rot_rand3;
uniform float4x3 rot_rand4;
float z, z0, w0, cloud, trel, zglob, struc, mat, bri, dist, radi;
float2 uv0, uv1, uv2, uv3, uva;
float3 sky, ambience;
static const float Hell =(_qa.w);
static const float3 skycolhi = 1;
static const float3 skycollo = 0.1;
static const float VisDist =(_qe.z);
float3 matcol (float x) {return float3(.2*x, pow(x-0.5,2), x*x*0.7) + float3(0.8, 0.75, 0.3);}
void PS(float4 _vDiffuse : COLOR, float2 _uv : TEXCOORD0, float2 _rad_ang : TEXCOORD1, out float4 _return_value : COLOR)
 {
float3 ret = 0;(_uv.xy) +=(_c7).zw/4;
mat =(tex2D(sampler_main,(_uv.xy)).xyz).r;
bri =(tex2D(sampler_main,(_uv.xy)).xyz).g*1.2; 
float land =(saturate) (2-2*(tex2D(sampler_main,(_uv.xy)).xyz).g);
dist = (1-(tex2D(sampler_main,(_uv.xy)).xyz).b)*0.99;
float ov =(saturate) (((_uv.xy).y-0.5)*1);
sky = lerp (skycolhi,skycollo,lerp (ov, 1-ov,(_qg.w)));
ambience = lerp (sky, Hell*.2,(_qg.y)*land); 
float2 uv1 =(_uv.xy)-float2(0.5,0);
float z = 0.05/(uv1.y);
float fogdens = tex2D(sampler_noise_hq, float2(uv1.x*z/4+(_c2.x)*0.0047, z)).r * land ;
ret = lerp (ambience, bri*matcol(mat)*ambience, pow(1-dist,(_qg.z)*fogdens));

_return_value = float4(ret.xyz, 1.0);
}

written by martin
END
problem setting pipeline: Shader compilation error
token prefix is g
token prefix is g

<SNIP>

/home/ewen/.Rack2/plugins/RPJVisualizer/res/presets_projectM/martin - Zen walk.milk(122) : Syntax error: expected ';' near 'written'
Failed to parse HLSL(step2) Comp shader
Source: 
uniform float4 texsize_pw_main;
uniform float4 texsize_pc_main;
uniform float4 texsize_noisevol_lq;
uniform float4 texsize_noisevol_hq;
uniform float4 texsize_noise_mq;
uniform float4 texsize_noise_lq_lite;
uniform float4 texsize_noise_lq;
uniform float4 texsize_noise_hq;
uniform float4 texsize_main;
uniform float4 texsize_fw_main;
uniform float4 texsize_fc_main;
uniform sampler2D sampler_pw_main;
uniform sampler2D sampler_pc_main;
uniform sampler3D sampler_noisevol_lq;
uniform sampler3D sampler_noisevol_hq;
uniform sampler2D sampler_noise_mq;
uniform sampler2D sampler_noise_lq_lite;
uniform sampler2D sampler_noise_lq;
uniform sampler2D sampler_noise_hq;
uniform sampler2D sampler_main;
uniform sampler2D sampler_fw_main;
uniform sampler2D sampler_fc_main;

uniform float4   rand_frame;    // random float4, updated each frame
uniform float4   rand_preset;   // random float4, updated once per *preset*
uniform float4   _c0;           // .xy: multiplier to use on UV's to paste
                                // an image fullscreen, *aspect-aware*
                                // .zw = inverse.
uniform float4   _c1, _c2, _c3, _c4;
uniform float4   _c5;           // .xy = scale, bias for reading blur1
                                // .zw = scale, bias for reading blur2
uniform float4   _c6;           // .xy = scale, bias for reading blur3
                                // .zw = blur1_min, blur1_max
uniform float4   _c7;           // .xy ~= float2(1024,768)
                                // .zw ~= float2(1/1024.0, 1/768.0)
uniform float4   _c8;           // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.3, ~1.3, ~5, ~20))
uniform float4   _c9;           // .xyzw ~= same, but using sin()
uniform float4   _c10;          // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.005, ~0.008, ~0.013,
                                //                 ~0.022))
uniform float4   _c11;          // .xyzw ~= same, but using sin()
uniform float4   _c12;          // .xyz = mip info for main image
                                // (.x=#across, .y=#down, .z=avg)
                                // .w = unused
uniform float4   _c13;          // .xy = blur2_min, blur2_max
                                // .zw = blur3_min, blur3_max
uniform float4   _qa;           // q vars bank 1 [q1-q4]
uniform float4   _qb;           // q vars bank 2 [q5-q8]
uniform float4   _qc;           // q vars ...
uniform float4   _qd;           // q vars
uniform float4   _qe;           // q vars
uniform float4   _qf;           // q vars
uniform float4   _qg;           // q vars
uniform float4   _qh;           // q vars bank 8 [q29-q32]

// note: in general, don't use the current time w/the *dynamic* rotations!

// four random, static rotations, randomized at preset load time.
// minor translation component (<1).
uniform float4x3 rot_s1;
uniform float4x3 rot_s2;
uniform float4x3 rot_s3;
uniform float4x3 rot_s4;

// four random, slowly changing rotations.
uniform float4x3 rot_d1;
uniform float4x3 rot_d2;
uniform float4x3 rot_d3;
uniform float4x3 rot_d4;

// faster-changing.
uniform float4x3 rot_f1;
uniform float4x3 rot_f2;
uniform float4x3 rot_f3;
uniform float4x3 rot_f4;

// very-fast-changing.
uniform float4x3 rot_vf1;
uniform float4x3 rot_vf2;
uniform float4x3 rot_vf3;
uniform float4x3 rot_vf4;

// ultra-fast-changing.
uniform float4x3 rot_uf1;
uniform float4x3 rot_uf2;
uniform float4x3 rot_uf3;
uniform float4x3 rot_uf4;

// Random every frame.
uniform float4x3 rot_rand1;
uniform float4x3 rot_rand2;
uniform float4x3 rot_rand3;
uniform float4x3 rot_rand4;
float z, z0, w0, cloud, trel, zglob, struc, mat, bri, dist, radi;
float2 uv0, uv1, uv2, uv3, uva;
float3 sky, ambience;
static const float Hell =(_qa.w);
static const float3 skycolhi = 1;
static const float3 skycollo = 0.1;
static const float VisDist =(_qe.z);
float3 matcol (float x) {return float3(.2*x, pow(x-0.5,2), x*x*0.7) + float3(0.8, 0.75, 0.3);}
void PS(float4 _vDiffuse : COLOR, float2 _uv : TEXCOORD0, float2 _rad_ang : TEXCOORD1, out float4 _return_value : COLOR)
 {
float3 ret = 0;(_uv.xy) +=(_c7).zw/4;
mat =(tex2D(sampler_main,(_uv.xy)).xyz).r;
bri =(tex2D(sampler_main,(_uv.xy)).xyz).g*1.2; 
float land =(saturate) (2-2*(tex2D(sampler_main,(_uv.xy)).xyz).g);
dist = (1-(tex2D(sampler_main,(_uv.xy)).xyz).b)*0.99;
float ov =(saturate) (((_uv.xy).y-0.5)*1);
sky = lerp (skycolhi,skycollo,lerp (ov, 1-ov,(_qg.w)));
ambience = lerp (sky, Hell*.2,(_qg.y)*land); 
float2 uv1 =(_uv.xy)-float2(0.5,0);
float z = 0.05/(uv1.y);
float fogdens = tex2D(sampler_noise_hq, float2(uv1.x*z/4+(_c2.x)*0.0047, z)).r * land ;
ret = lerp (ambience, bri*matcol(mat)*ambience, pow(1-dist,(_qg.z)*fogdens));

_return_value = float4(ret.xyz, 1.0);
}

**Comment by kockie69** [comment]
A new release has been sent to VCV yesterday which should include a fix for this issue.

**Comment by ContemporaryInsanity** [comment]
Back in 2.1.5

uniform float4   rand_frame;    // random float4, updated each frame
uniform float4   rand_preset;   // random float4, updated once per *preset*
uniform float4   _c0;           // .xy: multiplier to use on UV's to paste
                                // an image fullscreen, *aspect-aware*
                                // .zw = inverse.
uniform float4   _c1, _c2, _c3, _c4;
uniform float4   _c5;           // .xy = scale, bias for reading blur1
                                // .zw = scale, bias for reading blur2
uniform float4   _c6;           // .xy = scale, bias for reading blur3
                                // .zw = blur1_min, blur1_max
uniform float4   _c7;           // .xy ~= float2(1024,768)
                                // .zw ~= float2(1/1024.0, 1/768.0)
uniform float4   _c8;           // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.3, ~1.3, ~5, ~20))
uniform float4   _c9;           // .xyzw ~= same, but using sin()
uniform float4   _c10;          // .xyzw ~= 0.5 + 0.5 * cos(
                                //   time * float4(~0.005, ~0.008, ~0.013,
                                //                 ~0.022))
uniform float4   _c11;          // .xyzw ~= same, but using sin()
uniform float4   _c12;          // .xyz = mip info for main image
                                // (.x=#across, .y=#down, .z=avg)
                                // .w = unused
uniform float4   _c13;          // .xy = blur2_min, blur2_max
                                // .zw = blur3_min, blur3_max
uniform float4   _qa;           // q vars bank 1 [q1-q4]
uniform float4   _qb;           // q vars bank 2 [q5-q8]
uniform float4   _qc;           // q vars ...
uniform float4   _qd;           // q vars
uniform float4   _qe;           // q vars
uniform float4   _qf;           // q vars
uniform float4   _qg;           // q vars
uniform float4   _qh;           // q vars bank 8 [q29-q32]

// note: in general, don't use the current time w/the *dynamic* rotations!

// four random, static rotations, randomized at preset load time.
// minor translation component (<1).
uniform float4x3 rot_s1;
uniform float4x3 rot_s2;
uniform float4x3 rot_s3;
uniform float4x3 rot_s4;

// four random, slowly changing rotations.
uniform float4x3 rot_d1;
uniform float4x3 rot_d2;
uniform float4x3 rot_d3;
uniform float4x3 rot_d4;

// faster-changing.
uniform float4x3 rot_f1;
uniform float4x3 rot_f2;
uniform float4x3 rot_f3;
uniform float4x3 rot_f4;

// very-fast-changing.
uniform float4x3 rot_vf1;
uniform float4x3 rot_vf2;
uniform float4x3 rot_vf3;
uniform float4x3 rot_vf4;

// ultra-fast-changing.
uniform float4x3 rot_uf1;
uniform float4x3 rot_uf2;
uniform float4x3 rot_uf3;
uniform float4x3 rot_uf4;

// Random every frame.
uniform float4x3 rot_rand1;
uniform float4x3 rot_rand2;
uniform float4x3 rot_rand3;
uniform float4x3 rot_rand4;
float z, z0, w0, cloud, trel, zglob, struc, mat, bri, dist, radi;
float2 uv0, uv1, uv2, uv3, uva;
float3 sky, ambience;
static const float Hell =(_qa.w);
static const float3 skycolhi = 1;
static const float3 skycollo = 0.1;
static const float VisDist =(_qe.z);
float3 matcol (float x) {return float3(.2*x, pow(x-0.5,2), x*x*0.7) + float3(0.8, 0.75, 0.3);}
void PS(float4 _vDiffuse : COLOR, float2 _uv : TEXCOORD0, float2 _rad_ang : TEXCOORD1, out float4 _return_value : COLOR)
 {
float3 ret = 0;(_uv.xy) +=(_c7).zw/4;
mat =(tex2D(sampler_main,(_uv.xy)).xyz).r;
bri =(tex2D(sampler_main,(_uv.xy)).xyz).g*1.2; 
float land =(saturate) (2-2*(tex2D(sampler_main,(_uv.xy)).xyz).g);
dist = (1-(tex2D(sampler_main,(_uv.xy)).xyz).b)*0.99;
float ov =(saturate) (((_uv.xy).y-0.5)*1);
sky = lerp (skycolhi,skycollo,lerp (ov, 1-ov,(_qg.w)));
ambience = lerp (sky, Hell*.2,(_qg.y)*land); 
float2 uv1 =(_uv.xy)-float2(0.5,0);
float z = 0.05/(uv1.y);
float fogdens = tex2D(sampler_noise_hq, float2(uv1.x*z/4+(_c2.x)*0.0047, z)).r * land ;
ret = lerp (ambience, bri*matcol(mat)*ambience, pow(1-dist,(_qg.z)*fogdens));

_return_value = float4(ret.xyz, 1.0);
}

written by martin
END
problem setting pipeline: Shader compilation error

**Comment by kockie69** [comment]
Ok, there is a preset called Zen Walk (file is martin - Zen Walk.milk) that is causing this. You can remove it from your presets (in the plugin folder plugins\RPJVisualizer\res\presets_projectM). I will see if I can disable in someway that presets write to the stdout..
