### ISSUE TITLE
LFMEmbedded blacks out if left-side controls are out of view

### ISSUE THREAD

**Issue by jimallman** [kockie69/Visualizer#35]
Perhaps this is intended behavior? The viz is restored as soon as the left-side controls start to re-enter our view.

![Screen Shot 2022-11-18 at 11 20 37 AM](https://user-images.githubusercontent.com/446375/202752470-aa377efc-8467-4a64-b72d-af20dcf4d73e.png)

![Screen Shot 2022-11-18 at 11 21 03 AM](https://user-images.githubusercontent.com/446375/202752452-bbef56c5-dcd7-49db-b09d-d20d10131146.png)

![Screen Shot 2022-11-18 at 11 21 17 AM](https://user-images.githubusercontent.com/446375/202752444-69488aeb-c76b-4b31-b8fa-f46ba8bd0949.png)

**Comment by kockie69** [comment]
It is a known issue (to me) and not intended. No idea at the moment if it can be solved. Will have a look.

**Comment by kockie69** [comment]
On windows and Linux this issue is fixed. Would be nice to get confirmation it also works on Mac. As it is solved on Linux and Windows I close this issue. Please reopen if not working on Mac.
