### ISSUE TITLE
LFMFull (full-screen on second monitor) disappears when clicking main Rack window

### ISSUE THREAD

**Issue by jimallman** [kockie69/Visualizer#36]
This is on Mac. I'd love to use LFMFull to create a persistent viz on a second monitor. This is working as expected (Enter key to get full screen), and I can see both windows (Rack and viz) at first. But then when I attempt to interact with Rack, the viz window disappears. 😞 

It seems to be minimized/hidden by the OS. I can find and restore the window (jumps back to full screen), but it hides again as soon as I interact with the main Rack window.

**Comment by jimallman** [comment]
On further exploration, the viz window also hides if I change focus to the finder or any other app. On changing focus back to Rack, the viz window remains hidden.

**Comment by kockie69** [comment]
This is already fixed and available for test. You can set if you want the window to be on top in the menu of the module.
Build your own or download from here: 

https://drive.google.com/drive/folders/1D0fXubpRCp_rHsIQbyyp0xLH5JdCukbj

Someone else raised it by mail.

**Comment by jimallman** [comment]
Sadly, the window still hides for me on Mac, **IF** it's fullscreen (done properly, with the Enter key).

**Comment by jimallman** [comment]
Fixed in latest dev. Bravo! 🥳
