### ISSUE TITLE
Playlist and collection feature (including favorites)

### ISSUE THREAD

**Issue by jimallman** [kockie69/Visualizer#38]
I've been thinking about how *I* want to manage presets. Marking some as favorites is nice, but I'd prefer a more general "preset list" feature. Here are my thoughts about how to hopefully keep it simple.

I'd like the ability to build multiple preset lists. Each is a simple list of preset names, just a text file with one name per line:
```
Geiss & Rovastar - Tokamak (Naked Intrusion Mix).milk
Aderassi - Antique Abyss.milk
LuxXx - God is Antiquated.milk
Aderassi - Antique Abyss.milk
```

The name of this file (`Great beat response.presets`) would also be the displayed name of this preset list (just as Milkdrop does w/ its preset files). A list could be used as a **playlist** (an ordered presentation, with duplicates allowed) or as a simple **collection** like Favorites (a list of unique names, without any particular order).

### The Simplest Thing That Could Possibly Work (phase one)

An initial version could let the user build and name these text files manually. This could be streamlined by adding a feature to the Visualizer's right-click menu, something like "Copy preset name to clipboard". This would make it pretty quick to preview presets in the live viz, copy their names and past into a text file.

The other main requirement is that Visualizer let you "load" a preset list and navigate through _its_ contents instead of the full preset collection. The presets would still come from the big preset folder, but the Next/Previous and preset search features would use this ordered list instead of the alphabetical list of all presets. This would require one more feature in the right-click  menu, something like "Load preset list..." (and "Load All Presets" if we've already loaded a list).

### Easy curation of Favorites (phase two)

There might be a pre-existing preset list file `Favorites.presets`, or it could be created as soon as the user chooses (from the right-click menu) "Add to favorites". Once the favorites collection exists, they can also choose "Remove from favorites" if the current preset is already listed there. (These functions would simply add or remove the current preset's name from the Favorites file.)

The user can review their favorites by using the "Load preset list..." feature described above; in its simplest form, this could open a file browser in the expected location. So the Favorites feature would not require the manual editing of text files as in phase one. Or this could be presented using a "favorites-only" filter option (toggle w/ checkmark) in the right-click menu. 

### Editing playlists and collections through the module GUI (phase three)

With some additional work, users could name and curate their own playlists without using a text editor. This could work entirely through the module's right-click menu, or maybe in a dedicated right-click menu just on the viz canvas. It might work something like this:

  - Rt-click on viz canvas to get this menu:
      - Add current preset to playlist...
        - [list of user's playlist files]
        - Create new Playlist...   [prompts for its name, appending `.presets` if missing]
      - Insert current preset before...
        - [list of user's playlist files]
              - [list of preset names in each playlist]

These operations would take immediate effect; there's no need for a "Save playlist" feature. I'm still pondering how to remove and re-order presets in a playlist... Hopefully this is enough to get your thoughts on the idea.

**Comment by jimallman** [comment]
> The other main requirement is that Visualizer let you "load" a preset list and navigate through its contents instead of the full preset collection.

On second thought, phase one could be _even simpler_: The code would look for a text file `playlist.presets`; if found, this file would populate the Visualizer instead of the full alphabetical listing of all presets. This would be invisible to the beginner, but documented for an advanced user.

**Comment by kockie69** [comment]
There is a branch, called favourites. That is where I am building the playlist functionality. A build us available:
https://github.com/kockie69/Visualizer/actions/runs/3595897482

You need a file called LFM.json which looks like this:

{
    "lists": [
        {
            "name": "Great beat response",
            "presets": ["Geiss & Rovastar - Tokamak (Naked Intrusion Mix).milk","Aderrasi - Antidote (Side Effects Mix).milk","LuxXx - God is Antiquated.milk","Che - Escape.milk"]
        },
        {
            "name": "More Great beat responses",
            "presets": ["Geiss & Rovastar - Tokamak (Naked Intrusion Mix).milk","Aderassi - Antique Abyss.milk","LuxXx - God is Antiquated.milk","Aderassi - Antique Abyss.milk"]
        } 
    ]
}

This file needs to be in the root of your rack folder. The module has now a button on the top which will become red if you press it. Select the list from the menu that you want to play from.

**Comment by jimallman** [comment]
Sounds cool! I'll check it out when I come up for air from my pet feature...

**Comment by kockie69** [comment]
The favourite branch now has 3 new features:
- Playlists can be saved
- You can add presets to existing lists
- You can delete presets from existing lists
next to do: 
- create lists from scratch from the module

**Comment by kockie69** [comment]
I have changed it completely. I am using he preset functionality from VCV now. So you can save and load the lists now using the preset menu. Will let you know when implemented (almost done)

**Comment by jimallman** [comment]
Sounds neat! Meanwhile, I'm chugging away on the dynamic-Q ("Qsense?") features. With both features working, this is going to be a monster.

**Comment by kockie69** [comment]
Ok , I think I got it working.You can save and load presets now using the preset of VCV. 
One thing I had to add, when you enable the playlist mode (button on top) I disable the cycling mode. This way I prevent projectm picking presets from the total playlist. I hope you find time to give it a try....
Again , it is in the favourite branch.

**Comment by jimallman** [comment]
You might want to keep an eye on this PR in projectM: https://github.com/projectM-visualizer/projectm/pull/672

**Comment by kockie69** [comment]
I am following that one on discord, but is based on a proposal I did together with some others to remove all the playlist stuff from projectm and leave it to the client. This should allow me to control what presets will be loaded when a switch needs to happen because of hardcut, timer or whatever.

**Comment by kblaschke** [comment]
Exactly. The core library now only has two methods to load presets (from a physical file or a buffer/stream), plus a callback that applications _can_ use to switch presets when projectM wants to (time-based soft cuts or beat-based hard cuts). It's totally fine though to take over the full control over switching presets in the application, the library will do as commanded.

I hope the features in the new playlist API are sufficient, but as always, real-world applications need to be implemented to put it to the test. Feedback is highly appreciated, amendments can still be made before the 4.0 release!

**Comment by kockie69** [comment]
If we are missing something we can add to the api ourselves as before 😉 but I think this should be sufficient.
