### ISSUE TITLE
build error with latest commit

### ISSUE THREAD

**Issue by davephillips** [kockie69/Visualizer#42]
Hi Robert !

commit 66efe01001f5c81c6e4eb516daa181d23af52933

VCV Rack 2.x local build for x86-64 MacOS Monterey 12.2

I've hit a snag compiling the last commit to main. Visualizer build fails here:

```
c++  -std=c++11 -stdlib=libc++  -I./src/include -ID:/a/Visualizer/Visualizer/src/include/ -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=x86-64 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_MAC -mmacosx-version-min=10.9  -c -o build/src/Renderer.cpp.o src/Renderer.cpp
...
src/Renderer.cpp:252:54: error: no member named '_projectMHandle' in 'ProjectMRenderer'
    auto presetName = projectm_get_preset_name(that->_projectMHandle, index);
                                               ~~~~  ^
```

Any suggestions ?

Best regards,

dp

**Comment by kockie69** [comment]
Hi Dave,

ProjectM has been updated so I fixed it. By accident committed a version where I started finishing new functionality.
Should be fixed now.
The new functionality is, that I have added the functionality to create playlists.

This version gives you the opportunity to create lists with visuals that you like, using the VCV preset functionality.  

The modules now have a button on the top which will become red if you press it. When pressed/active/red , the module is in playlist mode and will play your created list. When off, it will play the default list that contains the thousands of visuals.
 
When you are not in playlist mode, you can add visuals to your list by pressing the + button when a visual is playing that you like. A visual can only be added once. 

When in playlist mode, you can remove a visual from your playlist by pressing the - button. 
You can save and load lists by using the load and save preset lists in the module menu, which is standard vcv functionality.

Looking forward to your feedback.

**Comment by davephillips** [comment]
Updated the source, no problems compiling, the plugin appears to work fine in the embedded module. I'll check the full version in a bit. 

The add/delete button works as advertised. Very nice to have the playlist features. The save as preset also works perfectly.

Thanks, Robert, this is a very cool and fun plugin. 

dp
