### ISSUE TITLE
RPJ Visualizer 2.1.10 has an update-loop issue

### ISSUE THREAD

**Issue by rubyglow** [kockie69/Visualizer#45]
Hi Robert

The just updated RPJ Visualizer version 2.1.10 has an update-loop issue (again). Meaning, I update from within Rack, restart, and it wants to update to the same version over and over again.

OS: macOS 10.12.6, Intel
Rack: Pro 2.2.2, standalone

Thanks!

**Comment by kockie69** [comment]
This is very annoying and to be honest I have no idea where this is coming from. Is it actually updating or is it still version 2.1.9?

Of course there was this issue in the past where some devs had to change their code (including me for the SquinkLabs modules) but that is not something I use in these modules. Also it doesn't happen on my Linux and Windows machines. This is also the only mention of it (although there might of course be more people experiencing it). I am providing a new version later today. If this gets deployed by Andrew (will be version 2.1.11) I hope it will be fixed for you. As it might be something in the upload (maybe?)

**Comment by rubyglow** [comment]
It is actually updating and the manifest says version 2.1.10. I just removed the RPJVisualizer directory from plugins/ and updated a boat-load of plugins, incl. visualizer, from Rack. They all apply cleanly and only visualizer want's to update again.

Looking in the log there's this:

[2.980 info src/plugin.cpp:171 loadPlugin] Loading plugin from /Users/lab/Documents/Rack2/plugins/RPJVisualizer
[2.980 warn src/plugin.cpp:237 loadPlugin] Could not load plugin /Users/lab/Documents/Rack2/plugins/RPJVisualizer: Failed to load library /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib: dlopen(/Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib

Which means it's exactly the same as this one https://github.com/kockie69/RPJ/issues/72 that I logged the last time. So whatever you did last time will probably work again. Seems to maybe be a build-chain issue that only affects older macOS versions.

**Comment by kockie69** [comment]
Hi Lars,

Can you please try if the Mac version that is available here https://drive.google.com/drive/folders/1D0fXubpRCp_rHsIQbyyp0xLH5JdCukbj is working for you?
If so, I can ask Andrew to update the Mac install with this version and it should hopefully solve the issue.

Robert

**Comment by rubyglow** [comment]
Hi Robert

Unfortunately not, but it's a different symbol it's complaining about now:

```
[0.836 info src/plugin.cpp:269 extractPackages] Extracting package /Users/lab/Documents/Rack2/plugins/RPJVisualizer-2.1.11-mac-x64.vcvplugin

-----------

[3.189 info src/plugin.cpp:171 loadPlugin] Loading plugin from /Users/lab/Documents/Rack2/plugins/RPJVisualizer
[3.191 warn src/plugin.cpp:237 loadPlugin] Could not load plugin /Users/lab/Documents/Rack2/plugins/RPJVisualizer: Failed to load library /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib: dlopen(/Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib, 6): Symbol not found: _projectm_render_frame
  Referenced from: /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib
  Expected in: flat namespace
 in /Users/lab/Documents/Rack2/plugins/RPJVisualizer/plugin.dylib

```
All the best,
Lars

**Comment by kockie69** [comment]
Thanks for getting back to me. The good news is, I can reproduce this on my Linux distro. 
I am porting my builds to the standard VCV toolchain. So when I have fixed it for my Linux distro I will build a new one for Mac too.

**Comment by kockie69** [comment]
I have uploaded a new version. Hope this fixes the previous issue. It is again at the same location

https://drive.google.com/drive/folders/1D0fXubpRCp_rHsIQbyyp0xLH5JdCukbj

**Comment by rubyglow** [comment]
Yup, that did the trick. Thank you very much! 👍
