### ISSUE TITLE
Remove binaries from repository

### ISSUE THREAD

**Issue by cschol** [kockie69/Visualizer#47]
Please remove binaries like `plugin.dll` from the repository **and its history**.

In order to do this, you need to use a tool like [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/).
Just removing the files from via commits will **not work**.

Other than that the plugin builds successfully and the necessary changes have been pushed to the Rack Plugin Toolchain repo.

Thank you.

**Comment by kockie69** [comment]
Removed all using bfg:
*.dll
vs/*
*.a
*.s0
*.so.4
*.exe
