### ISSUE TITLE
Remove git operations from Makefile

### ISSUE THREAD

**Issue by cschol** [kockie69/Visualizer#48]
I found the issue with the library build.

The `Makefile` performs `git` operations (`submodule update`). It cannot do this and should rely on the build process (or user) to perform the correct version control operations to put the source directory in the correct state. The issue arises when building the plugin as a submodule, where the repository root in git's context is two levels higher than the plugin directory.

Please remove the `git submodule` invocations from the `Makefile`.

Thanks.

**Comment by kockie69** [comment]
These are all removed.
