### ISSUE TITLE
Visualizer for Arm64 ?

### ISSUE THREAD

**Issue by davephillips** [kockie69/Visualizer#49]
Hi Robert !

Will there be a version for native M1 ?

dp

**Comment by kockie69** [comment]
Working on it. I am building on in the toolchain now. I have the 2 mac versions building now (can't test them myself). So I can upload if you are interested. Otherwise you have to wait till publicly deployed by VCV.

**Comment by kockie69** [comment]
Latest version can be downloaded from here: https://drive.google.com/drive/folders/1D0fXubpRCp_rHsIQbyyp0xLH5JdCukbj

**Comment by kockie69** [comment]
Closed, as we entered testing phase
