### ISSUE TITLE
Visualizer 2.1.11 crashes Rack 2.4.1 when moving Beat Sensitivity knob up past 75%

### ISSUE THREAD

**Issue by fractalgee** [kockie69/Visualizer#50]
Mac arm64 build 2.1.11 of Visualizer crashes Rack 2.4.1 when pushing up the Beat Sensitivity knob past 75% (3/4 clockwise). Audio in connected and playlist is on

Crash backtrace is:

```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   plugin.dylib                  	       0x13250a318 BaseProjectMWidget::step() + 204
1   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
2   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
3   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
4   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
5   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
6   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
7   libRack.dylib                 	       0x103a124c8 rack::ui::ScrollWidget::step() + 24
8   libRack.dylib                 	       0x1039cf278 rack::app::RackScrollWidget::step() + 560
9   libRack.dylib                 	       0x103a196e8 rack::widget::Widget::step() + 64
10  libRack.dylib                 	       0x1039da0a0 rack::app::Scene::step() + 340
11  libRack.dylib                 	       0x103a1e65c rack::window::Window::step() + 1596
12  libRack.dylib                 	       0x103a1e008 rack::window::Window::run() + 40
13  Rack                          	       0x102f3a7e0 main + 3428
14  dyld                          	       0x18c9bbf28 start + 2236
```

Also crashes with same stack at default settings with audio in connected and leaving it run until presumably it wants to switch presets (playlist button on)

**Comment by kockie69** [comment]
If you rightclick the module, do you see the list of visuals?

**Comment by kockie69** [comment]
Wow, in some way I produced the crash myself too on Linux. Happy with that, as it doesn't seem to be a bug related to Mac. So I think it is related to an empty playlist and trying to switch to next visual in (empty) playlist. I think that bug has been around for a long time....

**Comment by fractalgee** [comment]
I do the list of all the visuals, in the right-click. So not an empty playlist as far as I can make out.... But seems to happen whenever it tries to switch from default preset to next one.

**Comment by kockie69** [comment]
But when it crashes you have the playlist active isn't it? I mean the top led is lighted isn't it?

**Comment by fractalgee** [comment]
Correct. Swicthes fine if not lit, but crashes when trying to switch with it on. So your guess is correct, playlist empty as I haven't added any visuals to it yet, so catch-22.

**Comment by kockie69** [comment]
New version has been uploaded to the same location that should fix the issue.

**Comment by fractalgee** [comment]
Just tested and yes, all good now! Thanks

**Comment by kockie69** [comment]
Perfect! Thanks for checking.
