### ISSUE TITLE
Crashes rack on restart, had to remove plugin to rescue patches

### ISSUE THREAD

**Issue by ContemporaryInsanity** [kockie69/Visualizer#9]
[5.194 fatal adapters/standalone.cpp:49 fatalSignalHandler] Fatal signal 11. Stack trace:
17: ./Rack() [0x403c8d]
16: /lib/x86_64-linux-gnu/libc.so.6(+0x42520)
15: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x33fbf3)
14: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x326b55)
13: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x3e0228)
12: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x22bd28)
11: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x22d9e7)
10: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x3c3d0d)
9: /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so(+0x3c3df2)
8: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(+0x896ad)
7: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(+0x63598)
6: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(+0x5a6c3)
5: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(+0x4d732)
4: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(ProjectMRenderer::renderLoop(mySettings, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)+0x16e)
3: /home/ewen/.Rack2/plugins/RPJVisualizer/plugin.so(+0x42ba7)
2: ./libRack.so(+0x82eb60)
1: /lib/x86_64-linux-gnu/libc.so.6(+0x94947)
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x44)

**Comment by kockie69** [comment]
I am working on it.

**Comment by kockie69** [comment]
The problem seems to be solved, and has been confirmed by one person till now. But be helpful for me if you can see if this version works for you. Thanks in advance.

[Mac-2.1.2 (9).zip](https://github.com/kockie69/Visualizer/files/9738921/Mac-2.1.2.9.zip)

**Comment by ContemporaryInsanity** [comment]
I'm not set up to build from source at the moment and don't really have time, can you supply a linux binary?

**Comment by kockie69** [comment]
Oh, sorry my mistake. Thought you were on Mac. Let me do some more testing
on the Linux version first.

**Comment by kockie69** [comment]
[Linux-2.1.2.zip](https://github.com/kockie69/Visualizer/files/9740364/Linux-2.1.2.zip)

**Comment by kockie69** [comment]
This version has also been released last night by the VCV team. So can you please test again? 
I tested on Ubuntu 22.04.1 and it is working for me.

**Comment by ContemporaryInsanity** [comment]
Seems ok so far, thanks.

Could you save the window size & position?

**Comment by kockie69** [comment]
Thanks for testing. Yes, I think that should be possible. Might be some
challenges around availability of other monitors/screens. Like what should
happen if not available?
Can you please create an issue in github for it? And your requirements
please? Nice one to look into.

Op zo 9 okt. 2022 om 10:13 schreef Ewen Bates ***@***.***>:

**Comment by kockie69** [comment]
Can you test this version for me? 
This version should also save the position of the window and restore when vcv is restarted.

Thanks.

[Linux-2.1.2.zip](https://github.com/kockie69/Visualizer/files/9763365/Linux-2.1.2.zip)

**Comment by ContemporaryInsanity** [comment]
Saves & restores position ok but ignores size.

**Comment by kockie69** [comment]
That was not built in but now is

[Linux-2.1.2.zip](https://github.com/kockie69/Visualizer/files/9763867/Linux-2.1.2.zip)

**Comment by ContemporaryInsanity** [comment]
Looking good.

Beat Sensitivity; two buttons, no visual feedback re. setting, wouldn't a knob be better?

**Comment by kockie69** [comment]
That is an interesting observation. I am wondering now why there is no visual feedback. If you try in the embedded, you will see there is feedback. 
I have tried to do it with a knob in earlier experiments, but that failed. If you are interested I can explain why. But it has to do with the api of Projectm, the engine that I use for this plugin. It only accepts up and down clicks. 
So, I will create an issue to find out why there is no feedback in the windowed version

**Comment by ContemporaryInsanity** [comment]
Noted.

There is no feedback in the embedded version here, just blank fields appearing:

![image](https://user-images.githubusercontent.com/12547379/195321213-a4938cd8-d5fa-4570-956e-dcb848f47a5b.png)
